export const LOAD_BOTS = 'LOAD_BOTS';
export const LOAD_BOT_NAMES = 'LOAD_BOT_NAMES';

export const UPDATE_SKATEBOARD_TEXT = 'UPDATE_SKATEBOARD_TEXT';

export const SEARCH_BOTS = 'SEARCH_BOTS';

export const UPDATE_SELECTED_RESULT = 'UPDATE_SELECTED_RESULT';

export const CHOOSE_RESULT = 'CHOOSE_RESULT';

export const SEARCH_PARAMETERS = 'SEARCH_PARAMETERS';

export const EXECUTION_STARTED = 'EXECUTION_STARTED';
export const EXECUTION_COMPLETED = 'EXECUTION_COMPLETED';
export const EXECUTION_FAILED = 'EXECUTION_FAILED';

export const UNKNOWN_COMMAND = 'UNKNOWN_COMMAND';
export const REQUEST_PARAMETER = 'REQUEST_PARAMETER';

export const RESET = 'RESET';

export const MARK_SEARCH_FOR_BOTS = 'MARK_SEARCH_FOR_BOTS';
export const MARK_SEARCH_FOR_PARAMS = 'MARK_SEARCH_FOR_PARAMS';

export const UPDATE_BOT_STATUS = 'UPDATE_BOT_STATUS';
export const UPDATE_PARAM_STATUS = 'UPDATE_PARAM_STATUS';
