export const LOAD_BOTS = 'LOAD_BOTS';
export const LOAD_BOT_NAMES = 'LOAD_BOT_NAMES';

export const UPDATE_SKATEBOARD_TEXT = 'UPDATE_SKATEBOARD_TEXT';

export const SEARCH_BOTS = 'SEARCH_BOTS';

export const NEXT_RESULT = 'NEXT_RESULT';
export const PREVIOUS_RESULT = 'PREVIOUS_RESULT';

export const CHOOSE_RESULT = 'CHOOSE_RESULT';

export const SEARCH_PARAMETERS = 'SEARCH_PARAMETERS';

export const EXECUTE = 'EXECUTE';
export const UNKNOWN_COMMAND = 'UNKNOWN_COMMAND';
export const REQUEST_PARAMETER = 'REQUEST_PARAMETER';
export const INVALID_STRING = 'INVALID_STRING';

export const RESET = 'RESET';
